function traclet = low_level_feature(im, bb)
    nb = size(bb,1);
    features = struct('x',{}, ...
                      'y',{}, ...
                      's',{}, ...
                      'bb',{}, ...
                      'im',{}, ...
                      'id',{});
    for i=1:nb
        traclet(i).bb = bb(i,:);
        traclet(i).x = bb(i,2) + 0.5*bb(i,4);
        traclet(i).y = bb(i,1) + 0.5*bb(i,3);
        traclet(i).s = bb(i,3)*bb(i,4);
        traclet(i).im = im(bb(i,2):bb(i,2)+bb(i,4), bb(i,1):bb(i,1)+bb(i,3), :);
    end
end